name: Protocol Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run main file
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          python3 src/main.py --version_major 1 --version_minor 0 --message_type 0 \
          --dest_ipv6 "2001:0db8:85a3:0000:0000:8a2e:0370:7334" --dest_port 12345 \
          --source_ipv6 "2001:0db8:85a3:0000:0000:8a2e:0370:1111" --source_port 54321 \
          --sequence_number 1 --message_content "Hello, LEO Satellite!"

      - name: Run unit tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          python3 test/test_bob2_protocol.py \
          --version_major 1 --version_minor 0 --message_type 1 \
          --dest_ipv6 "2001:0db8:85a3:0000:0000:8a2e:0370:7334" --dest_port 12345 \
          --source_ipv6 "2001:0db8:85a3:0000:0000:8a2e:0370:1111" --source_port 54321 \
          --sequence_number 42 --message_content "Test Message"
